NYC Taxi Trip Duration Challenge
================================

The task at hand is to predict taxi trip durations in NYC using
variables such as pickup time, geo-coordinates, number of passengers,
etc.

Data Import
-----------

Let’s read in the training and testing data files. We will use the
stringsAsFactors FALSE since we don’t want all the strings to be
converted to factor variables as some of the date columns would be
stored as characters too.

``` r
test <- read.csv('test.csv', header = TRUE, stringsAsFactors = FALSE)
train <- read.csv('train.csv', header = TRUE, stringsAsFactors = FALSE)
```

What do the datasets look like?
-------------------------------

    ## Observations: 1,458,644
    ## Variables: 11
    ## $ id                 <chr> "id2875421", "id2377394", "id3858529", "id3...
    ## $ vendor_id          <int> 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2...
    ## $ pickup_datetime    <chr> "2016-03-14 17:24:55", "2016-06-12 00:43:35...
    ## $ dropoff_datetime   <chr> "2016-03-14 17:32:30", "2016-06-12 00:54:38...
    ## $ passenger_count    <int> 1, 1, 1, 1, 1, 6, 4, 1, 1, 1, 1, 4, 2, 1, 1...
    ## $ pickup_longitude   <dbl> -73.98215, -73.98042, -73.97903, -74.01004,...
    ## $ pickup_latitude    <dbl> 40.76794, 40.73856, 40.76394, 40.71997, 40....
    ## $ dropoff_longitude  <dbl> -73.96463, -73.99948, -74.00533, -74.01227,...
    ## $ dropoff_latitude   <dbl> 40.76560, 40.73115, 40.71009, 40.70672, 40....
    ## $ store_and_fwd_flag <chr> "N", "N", "N", "N", "N", "N", "N", "N", "N"...
    ## $ trip_duration      <int> 455, 663, 2124, 429, 435, 443, 341, 1551, 2...

    ## [1] "The structure of the training data is shown below - "

    ## Observations: 625,134
    ## Variables: 9
    ## $ id                 <chr> "id3004672", "id3505355", "id1217141", "id2...
    ## $ vendor_id          <int> 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1...
    ## $ pickup_datetime    <chr> "2016-06-30 23:59:58", "2016-06-30 23:59:53...
    ## $ passenger_count    <int> 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 4, 1, 1, 1, 1...
    ## $ pickup_longitude   <dbl> -73.98813, -73.96420, -73.99744, -73.95607,...
    ## $ pickup_latitude    <dbl> 40.73203, 40.67999, 40.73758, 40.77190, 40....
    ## $ dropoff_longitude  <dbl> -73.99017, -73.95981, -73.98616, -73.98643,...
    ## $ dropoff_latitude   <dbl> 40.75668, 40.65540, 40.72952, 40.73047, 40....
    ## $ store_and_fwd_flag <chr> "N", "N", "N", "N", "N", "N", "N", "N", "N"...

    ## [1] "The structure of the test data is shown below - "

We see that we have a LOT of training and testing data - around
1,458,644 observations in the training data and 625,134 observations in
the test data. Two variables present in the train data are not present
in the test data - these are `dropoff_datetime` and the output variable
`trip_duration`. <br>

Let’s add these variables with the value 0 in the test data for
consistency.

``` r
test$dropoff_datetime <- 0 # add dropoff_datetime
test$trip_duration <- 0 # add trip_duration
```
